#!/usr/bin/env node
/**
 * The Fitzpatrick sweep, as a markdown table.
 *
 *   npm run sweep          prints it
 *   npm run sweep -- --write   writes docs/SWEEP.md
 *
 * One look, computed for seven people across the range, with the shade the conventional rule
 * would have produced beside the one the engine uses. Generated from the engine rather than
 * written by hand, so the table in the submission cannot drift from what the code does. If a
 * change breaks the claim, regenerating the table shows it.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname;

const { selectLooks } = await import(join(ROOT, "src/lib/colorEngine/template.ts"));
const { hexToOklch, deltaE } = await import(join(ROOT, "src/lib/colorEngine/oklch.ts"));
const { ANALYSIS_FIXTURES } = await import(join(ROOT, "src/lib/fixtures/analysisFixtures.ts"));

const rows = [];
for (const fx of ANALYSIS_FIXTURES) {
  const looks = selectLooks(fx.colors, fx.fitzpatrick);
  // The boldest on show: a soft register sits close to her own colouring under either rule, so it
  // makes the weakest case for a decision that is real.
  const look =
    [...looks].sort(
      (a, b) =>
        ({ soft: 0, polished: 1, bold: 2 })[b.register] - ({ soft: 0, polished: 1, bold: 2 })[a.register],
    )[0] ?? looks[0];

  rows.push({
    label: fx.label,
    fitz: fx.fitzpatrick ?? "n/a",
    look: look.label,
    conventional: look.conventionalLip,
    conventionalChroma: hexToOklch(look.conventionalLip).c,
    adapted: look.lipColor,
    adaptedChroma: hexToOklch(look.lipColor).c,
    moved: deltaE(look.conventionalLip, look.lipColor),
    differing: looks.filter((l) => l.conventionalLip !== l.lipColor).length,
    total: looks.length,
  });
}

const swatch = (hex) => `\`${hex}\``;
const table = [
  "| Colouring | Fitz | Look | Placed the usual way | Placed for depth | ΔE moved | Looks affected |",
  "| --- | --- | --- | --- | --- | --- | --- |",
  ...rows.map(
    (r) =>
      `| ${r.label} | ${r.fitz} | ${r.look} | ${swatch(r.conventional)} (chroma ${r.conventionalChroma.toFixed(3)}) ` +
      `| ${swatch(r.adapted)} (chroma ${r.adaptedChroma.toFixed(3)}) | ${r.moved.toFixed(3)} | ${r.differing}/${r.total} |`,
  ),
].join("\n");

const doc = `# The Fitzpatrick sweep

Generated by \`npm run sweep\`. Do not edit by hand; regenerate it.

One look per person, computed across the fixture range, with the shade the conventional rule
would have produced beside the one the engine uses.

"Placed the usual way" means makeup colour sits below the skin's own lightness. That is a
fair-skin assumption: there is room below fair skin and almost none below deep skin, where what
room exists is the region sRGB cannot hold a saturated colour in at all. Both columns come from
the same engine, the same look and the same visibility guards. The only difference is that one
rule.

${table}

Two things to read off it.

**The rule does nothing until it is needed.** Across the five lighter fixtures the two columns are
identical and no look is affected. It is not a special case for deep skin; it is a rule that only
binds where there is no room below.

**The guard cannot rescue it.** The "usual way" column is the shade *after* the visibility guard
has run and tried to push it clear of the skin. On the deepest colouring it still arrives close to
black, because distance from the skin is not the same property as being a colour. Black is a
long way from skin and still not a lipstick.
`;

if (process.argv.includes("--write")) {
  const out = join(ROOT, "..", "docs", "SWEEP.md");
  writeFileSync(out, doc);
  console.log(`Wrote ${out}`);
} else {
  console.log(doc);
}
